https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

pip install keras (455+ MB)<br>Your First Deep Learning Project in Python with Keras Step-by-Step
The steps<br>

- Load Data
- Define Keras Model
-  Compile Keras Model
- Fit Keras Model
- Evaluate Keras Model
- Tie It All Together
- Make Predictions

In [1]:
# neural network with keras
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [6]:
# load the dataset
dataset = loadtxt('pima-indians-diabetes.data.csv', delimiter=',')

The variables<br>

**Input Variables (X):**<br>

1. Number of times pregnant
2. Plasma glucose concentration at 2 hours in an oral glucose tolerance test
3. Diastolic blood pressure (mm Hg)
4. Triceps skin fold thickness (mm)
5. 2-hour serum insulin (mu U/ml)
6. Body mass index (weight in kg/(height in m)^2)
7. Diabetes pedigree function
8. Age (years)

**Output Variables (y):**<br> 

1. Class variable (0 or 1)

In [10]:
dataset[0:3] # The data will be stored in a 2D array [rows, columns].

array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   ,  29.   ,   0.   ,  26.6  ,   0.351,
         31.   ,   0.   ],
       [  8.   , 183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672,
         32.   ,   1.   ]])

You can split the array into two arrays <br>
select first eight columns from index 0 to index 7 via the slice 0:8. <br>
then select the output column (the 9th variable) via index 8.

In [11]:
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]

In [12]:
X[:3]

array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ],
       [  1.   ,  85.   ,  66.   ,  29.   ,   0.   ,  26.6  ,   0.351,
         31.   ],
       [  8.   , 183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672,
         32.   ]])

In [17]:
y[:3]

array([1., 0., 1.])

** Models in Keras are defined as a sequence of layers.**<br>
- ensure the input layer has the correct number of input features.
- specify it when creating the first layer with the input_shape argument and setting it to (8,) for presenting the eight input variables as a vector.

- Fully connected layers are defined using the Dense class. 
- Specify the number of neurons in the layer as the first argument
- and the activation function using the activation argument.

- Sigmoid and Tanh activation functions were preferred for all layers. <br><br>
- The model expects rows of data with 8 variables
- The first hidden layer has 12 nodes and uses the relu activation function.

- The second hidden layer has 8 nodes and uses the relu activation function.
- The output layer has 1 node and uses the sigmoid activation function.

https://towardsdatascience.com/multi-layer-neural-networks-with-sigmoid-function-deep-learning-for-rookies-2-bf464f09eb7f

In [20]:

# define the keras model
model = Sequential()
model.add(Dense(12, input_shape=(8,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

** Compile Keras Model**
- training a network means finding the best set of weights to map inputs to outputs in your dataset.
<br>
- use cross entropy as the loss argument.
- choose loss functions based on your problem
- 
https://machinelearningmastery.com/how-to-choose-loss-functions-when-training-deep-learning-neural-networks/

**Learn**<br>
- configure a model for mean squared error and variants for regression problems.
- configure a model for cross-entropy and hinge loss functions for binary classification.
- configure a model for cross-entropy and KL divergence loss functions for multi-class classification.

- Regression Loss Functions
1. Mean Squared Error Loss
2. Mean Squared Logarithmic Error Loss
3. Mean Absolute Error Loss

https://machinelearningmastery.com/loss-and-loss-functions-for-training-deep-learning-neural-networks/

In [24]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Fit your model
-Train your model with loaded data by calling the fit() function

- Training occurs over epochs
- each epoch is split into batches.

- **Epoch**: One pass through all of the rows in the training dataset
- **Batch**: One or more samples considered by the model within an epoch before weights are updated<br>
https://machinelearningmastery.com/difference-between-a-batch-and-an-epoch/

In [25]:
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 9.3158 - accuracy: 0.5182
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 3.9066 - accuracy: 0.4583
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 1.6467 - accuracy: 0.4896
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 1.0730 - accuracy: 0.5599
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8664 - accuracy: 0.5938
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8197 - accuracy: 0.6172
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7829 - accuracy: 0.6536
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7376 - accuracy: 0.6549
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7096 - accuracy: 0.6497
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6929 - accuracy: 0.6562
Epoch 11/

77/77 [==============================] - 0s 2ms/step - loss: 0.5356 - accuracy: 0.7370
Epoch 84/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5151 - accuracy: 0.7604
Epoch 85/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5157 - accuracy: 0.7487
Epoch 86/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5036 - accuracy: 0.7643
Epoch 87/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5153 - accuracy: 0.7383
Epoch 88/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5134 - accuracy: 0.7461
Epoch 89/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5022 - accuracy: 0.7604
Epoch 90/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5334 - accuracy: 0.7396
Epoch 91/150
77/77 [==============================] - 0s 2ms/step - loss: 0.5141 - accuracy: 0.7513
Epoch 92/150
77/77 [==============================] - 0s 2ms/step - loss: 0.4977 - accuracy: 0.7604
Epoch 93/150


## Evaluate Keras Model
- evaluate the performance of the network on the same dataset.
- use the evaluate() function and pass it the same input and output used to train the model.
- This will generate a prediction for each input and output pair and collect scores, including the average loss and any metrics you have configured, such as accuracy.

- The evaluate() function will return a list with two values. The first will be the loss of the model on the dataset, and the second will be the accuracy of the model on the dataset. 


In [29]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: ', accuracy*100,",",  "Loss ", _)

24/24 [==============================] - 0s 2ms/step - loss: 0.4647 - accuracy: 0.7826
Accuracy:  78.25520634651184 , Loss  0.46467021107673645


In [30]:
# Make Predictions

# make probability predictions with the model
predictions = model.predict(X)

# round predictions 
rounded = [round(x[0]) for x in predictions]

24/24 [==============================] - 0s 2ms/step


In [32]:
rounded

[1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,


In [31]:

# make class predictions with the model
predictions = (model.predict(X) > 0.5).astype(int)

24/24 [==============================] - 0s 1ms/step


In [33]:
predictions

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [35]:
# summarize the first 5 cases
for i in range(5):
    print('%s => %d (expected %d)' % (X[i].tolist(), predictions[i], y[i]))


[6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0] => 1 (expected 1)
[1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0] => 0 (expected 0)
[8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0] => 1 (expected 1)
[1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0] => 0 (expected 0)
[0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0] => 1 (expected 1)
